name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build React app
      run: |
        npm run build

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Setup SSH key
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy
      env:
        SSHPASS: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        sshpass -e scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r dist/* root@mertalukas:/www/public/root/
